# Generated by Django 4.2.5 on 2023-09-14 07:59

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("utube", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Videoplaylist",
            fields=[
                ("playlist_name", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="playlist_video"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=None,
                        populate_from="playlist_name",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="videos",
            name="sub_title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="videos",
            name="playlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="utube.videoplaylist",
            ),
        ),
    ]
