# Generated by Django 4.2.5 on 2023-09-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utube", "0002_videoplaylist_videos_sub_title_videos_playlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="story_connect",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="story",
            name="top_rated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="videos",
            name="first_youuber",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="videos",
            name="top_rated",
            field=models.BooleanField(default=False),
        ),
    ]
