# Generated by Django 4.2.5 on 2023-09-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utube", "0003_story_story_connect_story_top_rated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playliststory",
            name="story_connect",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="videoplaylist",
            name="story_connect",
            field=models.BooleanField(default=False),
        ),
    ]
