# Generated by Django 4.2.5 on 2023-09-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utube", "0005_rename_story_connect_videoplaylist_first_youtuber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playliststory",
            name="top_rated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="videoplaylist",
            name="top_rated",
            field=models.BooleanField(default=False),
        ),
    ]
