# Generated by Django 4.2.5 on 2023-09-14 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("utube", "0006_playliststory_top_rated_videoplaylist_top_rated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vcomment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("msg", models.TextField()),
                (
                    "slug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="utube.videos"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scomment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("msg", models.TextField()),
                (
                    "slug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="utube.story"
                    ),
                ),
            ],
        ),
    ]
